PieDock: PieDock::ArgbSurfaceSizeMap Class Reference
PieDock::ArgbSurfaceSizeMap Class Reference
#include <ArgbSurfaceSizeMap.h>
Public Member Functions
ArgbSurfaceSizeMap (const ArgbSurface *)
virtual ~ArgbSurfaceSizeMap ()
const ArgbSurface & getSurface () const
virtual const ArgbSurface * getSurface (int, int)
virtual void setSurface (ArgbSurface *)
Protected Member Functions
virtual void clear ()
Detailed Description
Sizing ARGB surfaces
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
ArgbSurfaceSizeMap::ArgbSurfaceSizeMap (const ArgbSurface * s)
Initialize object
Parameters
s - some ARGB surface
ArgbSurfaceSizeMap::~ArgbSurfaceSizeMap () virtual
Clean up
References clear().
Member Function Documentation
void ArgbSurfaceSizeMap::clear () protected virtual
Clear map
Referenced by setSurface(), and ~ArgbSurfaceSizeMap().
const ArgbSurface * ArgbSurfaceSizeMap::getSurface (int width, int height) virtual
Return a sized version of the icon image
Parameters
width - width of surface in pixels
height - height of surface in pixels
References PieDock::Resampler::resample().
void ArgbSurfaceSizeMap::setSurface (ArgbSurface * s) virtual
Reset surface
Parameters
s - some ARGB surface
References clear().
The documentation for this class was generated from the following files:
src/ArgbSurfaceSizeMap.h
src/ArgbSurfaceSizeMap.cpp