PieDock: PieDock::Text Class Reference
PieDock::Text Class Reference
#include <Text.h>
Classes
class Color
class Font
class Metrics
Public Member Functions
Text (Display *, Drawable, Visual *, Font)
virtual void setColor (const Color)
virtual void draw (const int, const int, const std::string) const
virtual Metrics getMetrics (const std::string) const
Detailed Description
Text output
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
Text::Text (Display * d, Drawable da, Visual * v, Text::Font f)
Text
Parameters
d - display
da - drawable
v - visual
f - font object
References setColor().
Member Function Documentation
void Text::draw (const int x, const int y, const std::string s) const virtual
Draw a string into canvas
Parameters
x - x position
y - y position
s - string to write
Referenced by PieDock::PieMenuWindow::updateWithText().
Text::Metrics Text::getMetrics (const std::string s) const virtual
Determine metrics of given string
Parameters
s - some string
Referenced by PieDock::PieMenuWindow::updateWithText().
void Text::setColor (const Color c) virtual
Set foreground color
Parameters
c - color object
Referenced by Text().
The documentation for this class was generated from the following files:
src/Text.h
src/Text.cpp