PieDock: PieDock::PieMenuWindow Class Reference
PieDock::PieMenuWindow Class Reference
#include <PieMenuWindow.h>
Public Types
enum Placement { AroundCursor, IconBelowCursor }
Public Member Functions
PieMenuWindow (Application &)
virtual ~PieMenuWindow ()
bool appear (std::string="", Placement=AroundCursor)
void draw ()
bool processEvent (XEvent &)
Public Member Functions inherited from PieDock::TransparentWindow
TransparentWindow (Application &)
virtual ~TransparentWindow ()
const Window & getWindow () const
virtual void appear ()
Protected Types
typedef std::map< int,
Cartouche * > CartoucheMap
Protected Member Functions
virtual void show (Placement=AroundCursor)
virtual void hide ()
virtual void updateWithText ()
virtual bool performAction (Settings::Action)
virtual void place (Placement)
Protected Member Functions inherited from PieDock::TransparentWindow
Application * getApp () const
const int & getWidth () const
const int & getHeight () const
XSurface * getCanvas () const
const GC & getGc () const
virtual void show ()
virtual void hide () const
virtual void clear ()
virtual void update () const
Detailed Description
This object realizes the pie dock on screen
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
PieMenuWindow::PieMenuWindow (Application & a)
Initialize this window
Parameters
a - Application object
References PieDock::WindowManager::setWindowType().
PieMenuWindow::~PieMenuWindow () virtual
Clean up
Member Function Documentation
bool PieMenuWindow::appear (std::string n = "", PieMenuWindow::Placement p = AroundCursor)
Make window appear, returns false if there are no menu items
Parameters
n - menu name (optional)
p - where the menu should appear (optional)
References PieDock::PieMenu::setTwistForSelection(), PieDock::TransparentWindow::show(), and PieDock::PieMenu::update().
void PieMenuWindow::draw () virtual
(Re-)Draw contents
Reimplemented from PieDock::TransparentWindow.
References PieDock::TransparentWindow::clear(), PieDock::PieMenu::draw(), PieDock::PieMenu::isObsolete(), PieDock::TransparentWindow::update(), and updateWithText().
void PieMenuWindow::hide () protected virtual
Hide window
References PieDock::TransparentWindow::hide().
Referenced by performAction(), and processEvent().
bool PieMenuWindow::performAction (Settings::Action action) protected virtual
Perform action
Parameters
action - action to perform
References PieDock::Menu::change(), PieDock::Menu::execute(), hide(), and PieDock::PieMenu::turn().
Referenced by processEvent().
void PieMenuWindow::place (PieMenuWindow::Placement placement) protected virtual
Place window on Screen
Parameters
placement - where to place window
Referenced by show().
bool PieMenuWindow::processEvent (XEvent & event) virtual
Process event, this method returns true as long as it wants to keep processing events
Parameters
event - X event
Reimplemented from PieDock::TransparentWindow.
References PieDock::Settings::getButtonFunctions(), hide(), and performAction().
void PieMenuWindow::show (PieMenuWindow::Placement p = AroundCursor) protected virtual
Show window
Parameters
p - where to show (optional)
References place(), and PieDock::TransparentWindow::show().
void PieMenuWindow::updateWithText () protected virtual
Update window having text
References PieDock::Blender::blend(), PieDock::Text::draw(), PieDock::Menu::getItemTitle(), PieDock::Text::getMetrics(), and PieDock::TransparentWindow::update().
Referenced by draw().
The documentation for this class was generated from the following files:
src/PieMenuWindow.h
src/PieMenuWindow.cpp