PieDock: PieDock::Cartouche Class Reference
PieDock::Cartouche Class Reference
#include <Cartouche.h>
Classes
struct Details
Public Member Functions
Cartouche (int, int, int, unsigned int=0xff000000)
Public Member Functions inherited from PieDock::ArgbSurface
ArgbSurface (int, int)
Public Member Functions inherited from PieDock::Surface
Surface (const Surface &)
virtual ~Surface ()
unsigned char * getData () const
const int & getWidth () const
const int & getHeight () const
const int & getDepth () const
const int & getBytesPerPixel () const
const int & getBytesPerLine () const
const int & getPadding () const
const int & getSize () const
Surface & operator= (const Surface &)
Protected Member Functions
virtual void drawRectangle (int, int, int, int, unsigned int)
virtual void drawRoundedRectangle (int, int, int, int, int, unsigned int)
virtual void drawCurveSlices (Details &, int, int, unsigned char)
Additional Inherited Members
Public Types inherited from PieDock::Surface
enum ColorDepth { Indexed = 8, HighColor = 16, RGB = 24, ARGB = 32 }
Detailed Description
A plain solid rectangle with rounded corners
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
Cartouche::Cartouche (int w, int h, int r, unsigned int c = 0xff000000)
Create plain solid rectangle
Parameters
w - width of rectangle in pixels
h - height of rectangle in pixels
r - radius of rounded corner in pixels
c - color of rectangle (optional)
References drawRectangle(), and drawRoundedRectangle().
Member Function Documentation
void Cartouche::drawCurveSlices (Details & d, int x, int y, unsigned char n) protected virtual
Draw curve slices of a rounded rectangle
Parameters
d - details
x - x curve position
y - y curve position
n - alpha of neighbouring pixel
Referenced by drawRoundedRectangle().
void Cartouche::drawRectangle (int left, int top, int right, int bottom, unsigned int color) protected virtual
Draw a solid rectangle
Parameters
left - left corner of rectangle
top - top corner of rectangle
right - right corner of rectangle
bottom - bottom corner of rectangle
color - color of rectangle
Referenced by Cartouche(), and drawRoundedRectangle().
void Cartouche::drawRoundedRectangle (int left, int top, int right, int bottom, int radius, unsigned int color) protected virtual
Draw rounded rectangle
Parameters
left - left corner of rectangle
top - top corner of rectangle
right - right corner of rectangle
bottom - bottom corner of rectangle
radius - radius of a corner
color - color of rectangle
References drawCurveSlices(), and drawRectangle().
Referenced by Cartouche().
The documentation for this class was generated from the following files:
src/Cartouche.h
src/Cartouche.cpp