PieDock: PieDock::WindowManager Class Reference
PieDock::WindowManager Class Reference
#include <WindowManager.h>
Classes
class WindowList
Static Public Member Functions
static void activate (Display *, Window)
static void iconify (Display *, Window)
static void close (Display *, Window)
static Window getActive (Display *)
static Window getClientWindow (Display *, Window)
static std::string getTitle (Display *, Window)
static ArgbSurface * getIcon (Display *, Window)
static unsigned long getWorkspace (Display *, Window)
static unsigned long getNumberOfWorkspaces (Display *)
static unsigned long getCurrentWorkspace (Display *)
static bool getWorkspacePosition (Display *, unsigned long &, unsigned long &)
static bool getDesktopGeometry (Display *, unsigned long &, unsigned long &)
static bool isNormalWindow (Display *, Window)
static void setWindowType (Display *, Window, const char *)
static void sendClientMessage (Display *, Window, const char *, unsigned long=0, unsigned long=0, unsigned long=0, unsigned long=0, unsigned long=0)
static Atom getAtom (Display *, const char *)
Detailed Description
Interface to the window manager
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Member Function Documentation
void WindowManager::activate (Display * d, Window w) static
Activate, raise and switch to the workspace of some window
Parameters
d - display
w - window id
References PieDock::WorkspaceLayout::getWorkspaceLayout(), PieDock::WorkspaceLayout::isOnAnotherWorkspace(), and sendClientMessage().
Referenced by PieDock::Menu::execute().
void WindowManager::close (Display * d, Window w) static
Close some window
Parameters
d - display
w - window id
References sendClientMessage().
Referenced by PieDock::Menu::execute().
Window WindowManager::getActive (Display * d) static
Return currently active window
Parameters
d - display
Referenced by PieDock::Menu::update().
Atom WindowManager::getAtom (Display * d, const char * n) static
Get X internal atom
Parameters
d - display
n - name of atom
Referenced by getClientWindow(), getTitle(), isNormalWindow(), sendClientMessage(), and setWindowType().
Window WindowManager::getClientWindow (Display * d, Window w) static
Get client/content window from a possible frame/decor window
Parameters
d - display
w - window
Private class to stand in if XmuClientWindow is missing; didn't like the thought of having a depedency for this
References getAtom().
Referenced by PieDock::Menu::execute().
unsigned long WindowManager::getCurrentWorkspace (Display * d) static
Return numer of current workspace
Parameters
d - display
Referenced by PieDock::WorkspaceLayout::isOnAnotherWorkspace().
bool WindowManager::getDesktopGeometry (Display * d, unsigned long & w, unsigned long & h) static
Return dimensions of all workspaces
Parameters
d - display
w - sum of the width of all workspaces
h - sum of the height of all workspaces
ArgbSurface * WindowManager::getIcon (Display * d, Window w) static
Return icon of some window
Parameters
d - display
w - window id
Referenced by PieDock::Menu::update().
unsigned long WindowManager::getNumberOfWorkspaces (Display * d) static
Return number of workspaces
Parameters
d - display
std::string WindowManager::getTitle (Display * d, Window w) static
Return (visible) title of some window
Parameters
d - display
w - window id
References getAtom().
Referenced by PieDock::Menu::update().
unsigned long WindowManager::getWorkspace (Display * d, Window w) static
Return workspace of window
Parameters
d - display
w - window id
Referenced by PieDock::WorkspaceLayout::isOnAnotherWorkspace().
bool WindowManager::getWorkspacePosition (Display * d, unsigned long & x, unsigned long & y) static
Return current view of workspace
Parameters
d - display
x - horizontal position
y - vertical position
Referenced by PieDock::WorkspaceLayout::isOnAnotherWorkspace().
void WindowManager::iconify (Display * d, Window w) static
Iconify some window
Parameters
d - display
w - window id
Referenced by PieDock::Menu::execute().
bool WindowManager::isNormalWindow (Display * d, Window w) static
Returns true if given window is not a panel or dock or something like that
Parameters
d - display
w - window id
References getAtom().
Referenced by PieDock::Menu::update().
void WindowManager::sendClientMessage (Display * d, Window w, const char * message, unsigned long data0 = 0, unsigned long data1 = 0, unsigned long data2 = 0, unsigned long data3 = 0, unsigned long data4 = 0) static
Send a ClientMessage to some window
Parameters
d - display
w - target window
message - message to send
data0 - data (optional)
data1 - data (optional)
data2 - data (optional)
data3 - data (optional)
data4 - data (optional)
References getAtom().
Referenced by activate(), and close().
void WindowManager::setWindowType (Display * d, Window w, const char * type) static
Set window type
Parameters
d - display
w - target window
t - type
References getAtom().
Referenced by PieDock::PieMenuWindow::PieMenuWindow().
The documentation for this class was generated from the following files:
src/WindowManager.h
src/WindowManager.cpp