PieDock: PieDock::TransparentWindow Class Reference
PieDock::TransparentWindow Class Reference
#include <TransparentWindow.h>
Public Member Functions
TransparentWindow (Application &)
virtual ~TransparentWindow ()
const Window & getWindow () const
virtual void appear ()
virtual void draw ()
virtual bool processEvent (XEvent &)
Protected Member Functions
Application * getApp () const
const int & getWidth () const
const int & getHeight () const
XSurface * getCanvas () const
const GC & getGc () const
virtual void show ()
virtual void hide () const
virtual void clear ()
virtual void update () const
Detailed Description
A (possibly pseudo-)transparent window
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
TransparentWindow::TransparentWindow (Application & a)
Initialize object
Parameters
a - Application object
TransparentWindow::~TransparentWindow () virtual
Clean up
Member Function Documentation
void TransparentWindow::clear () protected virtual
Clear window for drawing
Referenced by PieDock::PieMenuWindow::draw(), and show().
void TransparentWindow::hide () const protected virtual
Hide window
Referenced by PieDock::PieMenuWindow::hide().
void TransparentWindow::show () protected virtual
Show window; the caller must ensure that the window is completely visible on the screen or XGetSubImage will fail !
References clear().
Referenced by PieDock::PieMenuWindow::appear(), and PieDock::PieMenuWindow::show().
void TransparentWindow::update () const protected virtual
Update window
Referenced by PieDock::PieMenuWindow::draw(), and PieDock::PieMenuWindow::updateWithText().
The documentation for this class was generated from the following files:
src/TransparentWindow.h
src/TransparentWindow.cpp