PieDock: PieDock::WindowStack Class Reference
PieDock::WindowStack Class Reference
#include <WindowStack.h>
Classes
struct WindowInfo
Public Types
typedef std::vector< WindowInfo > WindowInfos
Public Member Functions
WindowInfos & getWindowInfos ()
const bool hasWindows () const
void clearWindows ()
void addWindow (Display *, Window)
const Window getNextWindow ()
const Window getPreviousWindow ()
const bool isUnmapped ()
Detailed Description
Controller for windows
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Member Function Documentation
void WindowStack::addWindow (Display * d, Window w)
Add a window to menu item
Parameters
d - display
w - window to add
Referenced by PieDock::Menu::update().
const Window WindowStack::getNextWindow ()
Return next window
Referenced by PieDock::Menu::change(), and PieDock::Menu::execute().
const Window WindowStack::getPreviousWindow ()
Return previous window
Referenced by PieDock::Menu::execute().
const bool WindowStack::isUnmapped ()
Returns true if there's at least one window visible
The documentation for this class was generated from the following files:
src/WindowStack.h
src/WindowStack.cpp