PieDock: PieDock::ActiveIndicator Class Reference
PieDock::ActiveIndicator Class Reference
#include <ActiveIndicator.h>
Public Member Functions
ArgbSurfaceSizeMap * getSizeMap () const
const int getX (int s, int i) const
const int getY (int s, int i) const
virtual void load (std::string)
virtual void parseX (std::string)
virtual void parseY (std::string)
virtual void reset ()
Detailed Description
Active indicator
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Member Function Documentation
void ActiveIndicator::load (std::string f) virtual
Load image file
Parameters
f - PNG file to load
References PieDock::Png::load().
Referenced by PieDock::Settings::load().
void ActiveIndicator::parseX (std::string s) virtual
Parse horizontal position argument
Parameters
s - string describing position
Referenced by PieDock::Settings::load().
void ActiveIndicator::parseY (std::string s) virtual
Parse vertical position argument
Parameters
s - string describing position
Referenced by PieDock::Settings::load().
void ActiveIndicator::reset () virtual
Reset
Referenced by PieDock::Settings::load().
The documentation for this class was generated from the following files:
src/ActiveIndicator.h
src/ActiveIndicator.cpp