PieDock: PieDock::Blender Class Reference
PieDock::Blender Class Reference
#include <Blender.h>
Classes
struct Details
Public Types
enum Opacity { Transparent = 0, Translucent = 128, Opaque = 0xff }
Public Member Functions
Blender (Surface &)
virtual void blend (const ArgbSurface &, int, int, int=Opaque)
Protected Member Functions
virtual void blendInto32Bit (Details &)
virtual void blendInto24Bit (Details &)
virtual void blendInto16Bit (Details &)
Detailed Description
Blend ARGB surfaces into some other surface of arbitrary color depth
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
Blender::Blender (Surface & c)
Initialize blender
Parameters
c - canvas image of arbitrary color-depth
Member Function Documentation
void Blender::blend (const ArgbSurface & src, int x, int y, int a = Opaque) virtual
Blend ARGB surface into canvas
Parameters
src - ARGB surface to blend into canvas
x - left position in canvas (optional)
y - upper position in canvas (optional)
a - alpha value (optional)
References blendInto16Bit(), blendInto24Bit(), and blendInto32Bit().
Referenced by PieDock::PieMenu::draw(), PieDock::MenuItemWithWorkspaces::showWorkspace(), and PieDock::PieMenuWindow::updateWithText().
void Blender::blendInto16Bit (Details & details) protected virtual
Blend into HighColor image
Parameters
details - blending details
Referenced by blend().
void Blender::blendInto24Bit (Details & details) protected virtual
Blend into RGB image
Parameters
details - blending details
Referenced by blend().
void Blender::blendInto32Bit (Details & details) protected virtual
Blend into ARGB image
Parameters
details - blending details
Referenced by blend().
The documentation for this class was generated from the following files:
src/Blender.h
src/Blender.cpp