PieDock: PieDock::WorkspaceLayout Class Reference
PieDock::WorkspaceLayout Class Reference
#include <WorkspaceLayout.h>
Classes
struct WorkspacePosition
Public Types
enum PreferredVirtualLayout { Horizontal, Vertical, Square }
Public Member Functions
const unsigned long & getScreenWidth () const
const unsigned long & getScreenHeight () const
const unsigned long & getTotalWidth () const
const unsigned long & getTotalHeight () const
const int & getColumns () const
const int & getRows () const
const bool & isVirtual () const
bool isOnAnotherWorkspace (Window, WorkspacePosition &)
bool isOnAnotherWorkspace (Window, XWindowAttributes &, WorkspacePosition &)
Static Public Member Functions
static WorkspaceLayout * getWorkspaceLayout (Display *, PreferredVirtualLayout=Horizontal)
Detailed Description
Layout of workspaces
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Member Function Documentation
WorkspaceLayout * WorkspaceLayout::getWorkspaceLayout (Display * d, PreferredVirtualLayout l = Horizontal) static
Return singleton instance
Parameters
d - display
l - preferred layout of workspaces (optional)
Referenced by PieDock::WindowManager::activate(), and PieDock::Menu::update().
bool WorkspaceLayout::isOnAnotherWorkspace (Window w, WorkspacePosition & p)
Returns true if the given window is on another workspace
Parameters
w - window
p - workspace position
Referenced by PieDock::WindowManager::activate(), and PieDock::MenuItemWithWorkspaces::showWorkspace().
bool WorkspaceLayout::isOnAnotherWorkspace (Window w, XWindowAttributes & wa, WorkspacePosition & p)
Returns true if the given window is on another workspace
Parameters
w - window
wa - window attributes
p - workspace position
References PieDock::WindowManager::getCurrentWorkspace(), PieDock::WindowManager::getWorkspace(), and PieDock::WindowManager::getWorkspacePosition().
The documentation for this class was generated from the following files:
src/WorkspaceLayout.h
src/WorkspaceLayout.cpp