PieDock: PieDock::Menu Class Reference
PieDock::Menu Class Reference
#include <Menu.h>
Public Member Functions
Menu (Application *)
void setWindowBelowCursor (Window w)
const Window & getWindowBelowCursor () const
MenuItem * getSelected () const
const std::string & getName () const
virtual bool update (std::string, Window=0)
virtual void draw (int, int)
virtual bool change (Settings::Action=Settings::Launch)
virtual void execute (Settings::Action=Settings::Launch)
virtual std::string getItemTitle () const
Protected Member Functions
Application * getApp () const
void setSelected (MenuItem *s)
MenuItems * getMenuItems () const
virtual int run (std::string) const
Detailed Description
Abstract menu
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Constructor & Destructor Documentation
Menu::Menu (Application * a)
Initialize menu
Parameters
a - application
Member Function Documentation
bool Menu::change (Settings::Action a = Settings::Launch) virtual
Check if item points to another menu and if so, change to it
Parameters
a - action to execute (optional)
References PieDock::WindowStack::getNextWindow(), and update().
Referenced by PieDock::PieMenuWindow::performAction().
void Menu::execute (Settings::Action a = Settings::Launch) virtual
Execute some action for the seleced icon
Parameters
a - action to execute (optional)
References PieDock::WindowManager::activate(), PieDock::WindowManager::close(), PieDock::WindowManager::getClientWindow(), PieDock::WindowStack::getNextWindow(), PieDock::WindowStack::getPreviousWindow(), PieDock::WindowManager::iconify(), and run().
Referenced by PieDock::PieMenuWindow::performAction().
std::string Menu::getItemTitle () const virtual
Return item title
Referenced by PieDock::PieMenuWindow::updateWithText().
int Menu::run (std::string command) const protected virtual
Run some command
Parameters
command - command to execute
Referenced by execute().
bool Menu::update (std::string menuName, Window forWindow = 0) virtual
Update menu
Parameters
menuName - menu name
forWindow - first window of a list of open windows that belong to the same application (optional)
Reimplemented in PieDock::PieMenu.
References PieDock::WindowStack::addWindow(), PieDock::IconMap::createIcon(), PieDock::WindowManager::getActive(), PieDock::IconMap::getFillerIcon(), PieDock::IconMap::getIcon(), PieDock::WindowManager::getIcon(), PieDock::IconMap::getIconByName(), PieDock::IconMap::getMissingIcon(), PieDock::WindowManager::getTitle(), PieDock::WorkspaceLayout::getWorkspaceLayout(), PieDock::WindowManager::isNormalWindow(), PieDock::IconMap::saveIcon(), and PieDock::MenuItemWithWorkspaces::showWorkspace().
Referenced by change(), and PieDock::PieMenu::update().
The documentation for this class was generated from the following files:
src/Menu.h
src/Menu.cpp