PieDock: PieDock::Resampler Class Reference
PieDock::Resampler Class Reference
#include <Resampler.h>
Static Public Member Functions
static void resample (ArgbSurface &, ArgbSurface &)
Static Protected Member Functions
static void biLinear (ArgbSurface &, ArgbSurface &)
static void areaAveraging (ArgbSurface &, ArgbSurface &)
Detailed Description
Resample some surface
Author
Markus Fisch mf@ma.nosp@m.rkus.nosp@m.fisch.nosp@m..de
Member Function Documentation
void Resampler::areaAveraging (ArgbSurface & dest, ArgbSurface & src) static protected
Resample by area averaging; use this method for minification
Parameters
dest - new surface
src - source surface
Referenced by resample().
void Resampler::biLinear (ArgbSurface & dest, ArgbSurface & src) static protected
Resample by bi-linear filtering; use this method for magnification
Parameters
dest - new surface
src - source surface
Referenced by resample().
void Resampler::resample (ArgbSurface & dest, ArgbSurface & src) static
Resample surface
Parameters
dest - new surface
src - source surface
References areaAveraging(), and biLinear().
Referenced by PieDock::ArgbSurfaceSizeMap::getSurface().
The documentation for this class was generated from the following files:
src/Resampler.h
src/Resampler.cpp